/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Ventas;

import GUI.Compras.*;
import modulo.inventario.*;
import Control.ControlGUI;
import DTO.ProductoDTO;
import excepciones.NegocioException;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joelr
 */
public class frmProductoVendido extends javax.swing.JFrame {

    String id;
    ProductoDTO productoElegido;

    /**
     * Creates new form RegistrarProductoGUI
     *
     * @param id
     */
    public frmProductoVendido(String id) {
        initComponents();
        this.setExtendedState(frmProductoVendido.MAXIMIZED_BOTH);
        this.AcomodarContenido();
        this.id = id;
        try {
            productoElegido = ControlGUI.getInstancia().obtenerProductoPorID(this.id);
            this.inicial();
        } catch (NegocioException ex) {
            Logger.getLogger(frmProductoVendido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        lblUnidad = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        lblPrecioVenta = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblCalculoVenta = new javax.swing.JLabel();
        txtCalculoVenta = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        lblDescuento = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 600));

        pnlFormulario.setBackground(new java.awt.Color(204, 255, 204));
        pnlFormulario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFormularioMouseClicked(evt);
            }
        });
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSKU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKU.setText("SKU:");
        pnlFormulario.add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        pnlFormulario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad:");
        lblCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, -1));

        txtSKU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSKU.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 22));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 22));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setPreferredSize(new java.awt.Dimension(200, 50));
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        pnlFormulario.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 120, 22));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, 32));

        jButtonConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 111, 32));

        lblUnidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidad.setText("Unidad de Medida:");
        pnlFormulario.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 210, -1));

        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 120, 22));

        lblPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecioVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioVenta.setText("Precio Venta:");
        lblPrecioVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 30));

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtotal.setText("Subtotal:");
        pnlFormulario.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, -1));

        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubtotal.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 120, 22));

        lblCalculoVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCalculoVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculoVenta.setText("Calculo Venta:");
        lblCalculoVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblCalculoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 30));

        txtCalculoVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalculoVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtCalculoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 120, 22));

        txtDescuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDescuento.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 120, 22));

        lblDescuento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescuento.setText("Descuento:");
        lblDescuento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 160, 30));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(51, 102, 0));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Producto Vendido");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        try {
            ControlGUI.getInstancia().guardarDetallesVenta(id, Integer.valueOf(this.txtCantidad.getText()), Double.valueOf(this.txtDescuento.getText()),
                    Double.valueOf(this.txtSubtotal.getText()));
            ControlGUI.getInstancia().PasarInfoARegistrarVenta();

        } catch (NegocioException ex) {
            Logger.getLogger(frmProductoVendido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if (id == null) {
            try {
                ControlGUI.getInstancia().mostrarProductosRegistrados(1);
            } catch (NegocioException ex) {
                Logger.getLogger(frmProductoVendido.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost

    }//GEN-LAST:event_txtCantidadFocusLost

    private void pnlFormularioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFormularioMouseClicked
        this.CalculoSubtotal();
    }//GEN-LAST:event_pnlFormularioMouseClicked

    /**
     * Metodo para el ajuste de los componentes cuando la pantalla cambie de
     * tamaño.
     */
    private void AcomodarContenido() {
        JPanel panel = this.pnlFormulario;
        this.pnlFormulario.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.weightx = 1.0; // Cada componente se expandirá horizontalmente de manera uniforme.
        gbc.fill = GridBagConstraints.HORIZONTAL; // Hace que el componente llene el espacio horizontalmente.
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor del componente.

        // Columna 0
        gbc.gridx = 0;
        panel.add(this.lblSKU, gbc);
        gbc.gridy++;
        panel.add(this.lblNombre, gbc);

        // Columna 1
        gbc.gridx = 1;
        gbc.gridy = 0;
        panel.add(this.txtSKU, gbc);
        gbc.gridy++;
        panel.add(this.txtNombre, gbc);
        gbc.gridy = gbc.gridy + 5;
        panel.add(this.jButtonCancelar, gbc);
        gbc.gridy++;

        // Columna 2
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel.add(this.lblCantidad, gbc);
        gbc.gridy++;
        panel.add(this.lblPrecioVenta, gbc);
        gbc.gridy++;
        panel.add(this.lblCalculoVenta, gbc);
        gbc.gridy++;
        panel.add(this.lblDescuento, gbc);
        gbc.gridy++;
        panel.add(this.lblSubtotal, gbc);
        gbc.gridy++;

        // Columna 3
        gbc.gridx = 3;
        gbc.gridy = 0;
        panel.add(this.txtCantidad, gbc);
        int aux = gbc.gridy;
        gbc.gridy++;
        panel.add(this.txtPrecioVenta, gbc);
        gbc.gridy++;
        panel.add(this.txtCalculoVenta, gbc);
        gbc.gridy++;
        panel.add(this.txtDescuento, gbc);
        gbc.gridy++;
        panel.add(this.txtSubtotal, gbc);
        gbc.gridy = gbc.gridy + 2;
        panel.add(this.jButtonConfirmar, gbc);

        // Columna 4
        gbc.gridx = 4;
        gbc.gridy = aux;
        panel.add(this.lblUnidad, gbc);

    }

    private void inicial() throws NegocioException {
        id = productoElegido.getId();
        this.txtNombre.setEditable(false);
        this.txtSKU.setEditable(false);
        this.txtPrecioVenta.setEditable(false);
        this.txtCalculoVenta.setEditable(false);
        this.txtSubtotal.setEditable(false);
        this.txtCantidad.setText("0");
        this.txtDescuento.setText("0.0");
        if (productoElegido.getNombre() == null || productoElegido.getNombre().equalsIgnoreCase("")) {
            this.txtNombre.setText("No registrado");
        } else {
            this.txtNombre.setText(productoElegido.getNombre());
        }
        if (productoElegido.getSKU() == null || productoElegido.getSKU().equalsIgnoreCase("")) {
            this.txtSKU.setText("No registrado");
        } else {
            this.txtSKU.setText(productoElegido.getSKU());
            this.txtPrecioVenta.setText(Double.toString(productoElegido.getPrecioVenta()));

        }
    }

    private void CalculoSubtotal() {
        int cantidad = Integer.valueOf(this.txtCantidad.getText());
        Double precio = Double.valueOf(this.txtPrecioVenta.getText());
        Double descuento = Double.valueOf(this.txtDescuento.getText());
        Double calculoVenta = precio * cantidad;
        Double subtotal = (precio * cantidad) - descuento;
        this.txtCalculoVenta.setText(String.valueOf(calculoVenta));
        this.txtSubtotal.setText(String.valueOf(subtotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel lblCalculoVenta;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCalculoVenta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables

}
