/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Caja;

import GUI.Compras.*;
import GUI.Login.*;
import modulo.inventario.*;
import Control.ControlGUI;
import DTO.CajaDTO;
import excepciones.NegocioException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joelr
 */
public class frmAperturaCaja extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmAperturaCaja() {
        initComponents();
        this.setExtendedState(frmAperturaCaja.MAXIMIZED_BOTH);
        this.AcomodarContenido();
        try {
            ControlGUI.getInstancia().extraerSesionCajaActiva();
        } catch (NegocioException ex) {
            Logger.getLogger(frmAperturaCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        lblMontoInicial = new javax.swing.JLabel();
        txtMontoInicial = new javax.swing.JTextField();
        datePickerFecha = new com.github.lgooddatepicker.components.DatePicker();
        lblFecha = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 255));
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 150, 40));

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 150, 40));

        lblMontoInicial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMontoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMontoInicial.setText("Monto Inicial");
        pnlFormulario.add(lblMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 200, -1));

        txtMontoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoInicial.setPreferredSize(new java.awt.Dimension(200, 50));
        txtMontoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoInicialActionPerformed(evt);
            }
        });
        pnlFormulario.add(txtMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 200, 22));
        pnlFormulario.add(datePickerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 200, -1));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        pnlFormulario.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 200, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(204, 0, 204));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Apertura de Caja");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        //Campo vacío
        if(txtMontoInicial.getText() == null || txtMontoInicial.getText().length()<0 || txtMontoInicial.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Indique el monto inicial para abrir la sesion de la caja", "Información requerida", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            //Validar numberFormatException
            double montoInicial = Double.parseDouble(txtMontoInicial.getText());

            //Crear la cajaDTO
            CajaDTO caja = new CajaDTO(montoInicial);
            
            //Pasados filtros se abre la caja
            caja = ControlGUI.getInstancia().abrirCaja(caja);
            ControlGUI.getInstancia().extraerSesionCajaActiva();
            
            //Si no hubo errores
            JOptionPane.showMessageDialog(this, "Se ha abierto la caja con éxito", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
        }catch(NegocioException ne){
            JOptionPane.showMessageDialog(this, ne.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico válido para el monto inicial", "Formato inválido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        ControlGUI.getInstancia().mostrarMenuCaja();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void txtMontoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoInicialActionPerformed
    private void AcomodarContenido() {
        JPanel panel = this.pnlFormulario;
        this.pnlFormulario.setLayout(new GridBagLayout()); // Permite centrar componentes dentro
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.insets = new Insets(2, 2, 2, 2); // Margen alrededor del componente
        gbc.anchor = GridBagConstraints.CENTER; // Centrado en la celda
        gbc.weightx = 1.0; // Espacio extra para centrar horizontalmente

        // Columna 0
//        gbc.gridx = 0;
        this.pnlFormulario.add(this.lblFecha, gbc);
        gbc.gridy++;
        this.pnlFormulario.add(this.datePickerFecha, gbc);
        this.datePickerFecha.setDateToToday();
        this.datePickerFecha.setEnabled(false);
        gbc.gridy++;
        this.pnlFormulario.add(this.lblMontoInicial, gbc);
        gbc.gridy++;
        this.pnlFormulario.add(this.txtMontoInicial, gbc);
        gbc.gridy++;
        this.pnlFormulario.add(this.jButtonConfirmar, gbc);
        this.jButtonConfirmar.setPreferredSize(new Dimension(150, 35));
        gbc.gridy++;
        this.pnlFormulario.add(this.jButtonVolver, gbc);
        this.jButtonVolver.setPreferredSize(new Dimension(150, 35));
        this.add(this.pnlFormulario, BorderLayout.CENTER);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAperturaCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerFecha;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMontoInicial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtMontoInicial;
    // End of variables declaration//GEN-END:variables

}
