/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Caja;

import modulo.inventario.*;
import Control.ControlGUI;
import DTO.CajaDTO;
import excepciones.NegocioException;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joelr
 */
public class frmCierreCaja extends javax.swing.JFrame {

    String id;

    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmCierreCaja() {
        initComponents();
        this.setExtendedState(frmCierreCaja.MAXIMIZED_BOTH);
        this.AcomodarContenido();
        this.lblTitulo.setText("Cierre de caja");
        this.jButtonConfirmar.setText("Cerrar");
        try {
            ControlGUI.getInstancia().extraerSesionCajaActiva();
        } catch (NegocioException ex) {
            Logger.getLogger(frmCierreCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //llenar con los datos de la sesión de caja activa
        llenarCamposSesion();
    }

//    public frmCierreCaja(String id) {
//        initComponents();
//        this.setExtendedState(frmCierreCaja.MAXIMIZED_BOTH);
//        this.AcomodarContenido();
//        this.id = id;
//        this.lblTitulo.setText("Actualizar Producto");
//        this.jButtonConfirmar.setText("Actualizar");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMontoFinal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtMontoFinal = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblNumeroTotalVentas = new javax.swing.JLabel();
        txtNumeroTotalVentas = new javax.swing.JTextField();
        lblCierre = new javax.swing.JLabel();
        txtCierre = new javax.swing.JTextField();
        datePickerFecha = new com.github.lgooddatepicker.components.DatePicker();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 600));

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 255));
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha");
        pnlFormulario.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 90, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        pnlFormulario.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));

        lblMontoFinal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMontoFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMontoFinal.setText("Monto Final");
        lblMontoFinal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setEnabled(false);
        txtTotal.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 22));

        txtMontoFinal.setEnabled(false);
        txtMontoFinal.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 22));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, 32));

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConfirmar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 111, 32));

        txtCantidad.setEnabled(false);
        txtCantidad.setPreferredSize(new java.awt.Dimension(200, 50));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        pnlFormulario.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 120, 22));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad de Productos Vendidos");
        lblCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 370, 30));

        lblNumeroTotalVentas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumeroTotalVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroTotalVentas.setText("Numero Total de Ventas");
        pnlFormulario.add(lblNumeroTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        txtNumeroTotalVentas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroTotalVentas.setEnabled(false);
        txtNumeroTotalVentas.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtNumeroTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 120, 22));

        lblCierre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCierre.setText("Notas de Cierre");
        pnlFormulario.add(lblCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        txtCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCierre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 280, 110));

        datePickerFecha.setEnabled(false);
        pnlFormulario.add(datePickerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(204, 0, 204));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cierre de caja");
        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        //Campo vacío
        String cierre = "Sin observaciones";
        if(txtCierre.getText() != null || !txtCierre.getText().equals("")){
            cierre = txtCierre.getText();
        }
        
        try{
            ControlGUI.getInstancia().cerrarCaja(cierre);
            JOptionPane.showMessageDialog(this, "Se ha cerrado la sesión de la caja!", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
        }catch(NegocioException ne){
            JOptionPane.showMessageDialog(this, ne.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        ControlGUI.getInstancia().mostrarMenuCaja();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    /**
     * Metodo para el ajuste de los componentes cuando la pantalla cambie de
     * tamaño.
     */
    private void AcomodarContenido() {
        JPanel panel = this.pnlFormulario;
        this.pnlFormulario.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.weightx = 1.0; // Cada componente se expandirá horizontalmente de manera uniforme.
        gbc.fill = GridBagConstraints.CENTER; // Hace que el componente llene el espacio horizontalmente.
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor del componente.

        // Columna 0
        gbc.gridx = 0;
        panel.add(this.lblFecha, gbc);
        gbc.gridy++;
        panel.add(this.datePickerFecha, gbc);
        this.datePickerFecha.setDateToToday();
        this.datePickerFecha.setEnabled(false);
        gbc.gridy++;
        panel.add(this.lblTotal, gbc);
        gbc.gridy++;
        panel.add(this.txtTotal, gbc);
        gbc.gridy++;
        panel.add(this.lblMontoFinal, gbc);
        gbc.gridy++;
        panel.add(this.txtMontoFinal, gbc);
        gbc.gridy++;
        panel.add(this.jButtonCancelar, gbc);
        this.jButtonCancelar.setPreferredSize(new Dimension(150, 35));
        gbc.gridy++;

        // Columna 1
        gbc.gridx = 1;
        gbc.gridy = 0;
        panel.add(this.lblCantidad, gbc);
        gbc.gridy++;
        panel.add(this.txtCantidad, gbc);
        gbc.gridy++;
        panel.add(this.lblNumeroTotalVentas, gbc);
        gbc.gridy++;
        panel.add(this.txtNumeroTotalVentas, gbc);
        gbc.gridy++;
        panel.add(this.lblCierre, gbc);
        gbc.gridy++;
        panel.add(this.txtCierre, gbc);
        gbc.gridy++;
        panel.add(this.jButtonConfirmar, gbc);
        this.jButtonConfirmar.setPreferredSize(new Dimension(150, 35));
        gbc.gridy++;

    }
    
    private void llenarCamposSesion(){
        //Obtenemos la sesión activa
        CajaDTO sesionCaja = ControlGUI.getInstancia().getSesionCajaActiva();
        
        //llenamos los txt
        txtCantidad.setText(sesionCaja.getCantidadDeProductos().toString());
        txtCierre.setText(sesionCaja.getObservacionesCierre());
        txtMontoFinal.setText(sesionCaja.getMontoFinalEstimado().toString());
        txtNumeroTotalVentas.setText(sesionCaja.getNumeroDeVentas().toString());
        txtTotal.setText(sesionCaja.getTotalVentas().toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCierreCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerFecha;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCierre;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMontoFinal;
    private javax.swing.JLabel lblNumeroTotalVentas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCierre;
    private javax.swing.JTextField txtMontoFinal;
    private javax.swing.JTextField txtNumeroTotalVentas;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
