/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Login;

import Control.ControlGUI;
import modulo.inventario.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author joelr
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonInventario1 = new javax.swing.JButton();
        jButtonCompras = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jButtonCajas = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 700));
        setSize(new java.awt.Dimension(850, 700));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 153));
        pnlFormulario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnlFormularioComponentResized(evt);
            }
        });
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, 40));

        jButtonInventario1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonInventario1.setText("Inventario");
        jButtonInventario1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFormulario.add(jButtonInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 130, 40));

        jButtonCompras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCompras.setText("Compras");
        jButtonCompras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFormulario.add(jButtonCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 40));

        jButtonVentas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVentas.setText("Ventas");
        jButtonVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFormulario.add(jButtonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 130, 40));

        jButtonCajas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCajas.setText("Cajas");
        jButtonCajas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFormulario.add(jButtonCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, 40));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(102, 51, 0));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Menu Principal");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 32, -1, -1));

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlFormularioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlFormularioComponentResized

    }//GEN-LAST:event_pnlFormularioComponentResized

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
      
    }//GEN-LAST:event_formWindowStateChanged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       ControlGUI.getInstancia().mostrarLogin();
       this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed


    ;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCajas;
    private javax.swing.JButton jButtonCompras;
    private javax.swing.JButton jButtonInventario1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables

}
