/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Compras;

import modulo.inventario.*;
import Control.ControlGUI;
import DTO.ProductoDTO;
import excepciones.NegocioException;
import excepciones.PersistenciaException;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author joelr
 */
public class frmConsultarCompras extends javax.swing.JFrame {

    GridBagConstraints gbc = new GridBagConstraints();
    int aux = 0;
    int fila = 0;

    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmConsultarCompras() throws NegocioException {
        initComponents();
        this.setExtendedState(frmConsultarCompras.MAXIMIZED_BOTH);
        this.AcomodarContenido();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        lblNombreProducto = new javax.swing.JLabel();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        txtNombreProducto = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        datePickerInicio = new com.github.lgooddatepicker.components.DatePicker();
        lblFechaFin = new javax.swing.JLabel();
        datePickerFin = new com.github.lgooddatepicker.components.DatePicker();
        lblProveedor = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 204, 153));
        pnlFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFondoMouseClicked(evt);
            }
        });
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setBackground(new java.awt.Color(255, 204, 153));
        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        pnlFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 130, 40));

        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("Nombre Producto: ");
        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlFondo.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 210, -1));

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Nombre", "Cantidad", "PrecioCompra", "Fecha", "Hora", "Proveedor", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableComprasFocusLost(evt);
            }
        });
        jTableCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComprasMouseClicked(evt);
            }
        });
        jScrollPaneProductos.setViewportView(jTableCompras);
        if (jTableCompras.getColumnModel().getColumnCount() > 0) {
            jTableCompras.getColumnModel().getColumn(0).setResizable(false);
            jTableCompras.getColumnModel().getColumn(1).setResizable(false);
            jTableCompras.getColumnModel().getColumn(2).setResizable(false);
            jTableCompras.getColumnModel().getColumn(3).setResizable(false);
            jTableCompras.getColumnModel().getColumn(4).setResizable(false);
            jTableCompras.getColumnModel().getColumn(5).setResizable(false);
            jTableCompras.getColumnModel().getColumn(6).setResizable(false);
            jTableCompras.getColumnModel().getColumn(7).setResizable(false);
        }

        pnlFondo.add(jScrollPaneProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 890, -1));

        txtNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFondo.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 190, 22));

        lblFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaInicio.setText("Fecha Inicio:");
        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFondo.add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 170, -1));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setBackground(new java.awt.Color(255, 204, 153));
        jButtonEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        pnlFondo.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 130, 40));

        jButtonConfirmar.setBackground(new java.awt.Color(255, 204, 153));
        jButtonConfirmar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        pnlFondo.add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 130, 40));
        pnlFondo.add(datePickerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, -1, -1));

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaFin.setText("Fecha Fin:");
        lblFechaFin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFondo.add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 170, -1));
        pnlFondo.add(datePickerFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, -1));

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProveedor.setText("Proveedor: ");
        pnlFondo.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 210, -1));

        txtProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProveedor.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFondo.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 190, 22));

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(102, 51, 0));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrar Compra");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed

        ControlGUI.getInstancia();
        this.dispose();


    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
//        if (aux == 0) {
//
//            this.jButtonConfirmar.setText("Eliminar");
//            this.jButtonEliminar.setVisible(true);
//            String id = Integer.toString(fila);
//            System.out.println(id);
//            try {
//                String nombre = this.jTableProductos.getValueAt(fila, 1).toString();
//                System.out.println(nombre);
//                ControlGUI.getInstancia().EliminarProducto(ControlGUI.getInstancia().obtenerProductoPorNombre(nombre).getId());
//                JOptionPane.showMessageDialog(rootPane, "Registro Eliminado con exito");
//            } catch (NegocioException | PersistenciaException ex) {
//                Logger.getLogger(frmComprasRegistradas.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed


    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jTableComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComprasMouseClicked

        fila = this.jTableCompras.getSelectedRow();
        this.jButtonEliminar.setVisible(true);
    }//GEN-LAST:event_jTableComprasMouseClicked

    private void jTableComprasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableComprasFocusLost

    }//GEN-LAST:event_jTableComprasFocusLost

    private void pnlFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFondoMouseClicked
        if (fila >= 0) {
            this.jButtonEliminar.setVisible(false);

        }
    }//GEN-LAST:event_pnlFondoMouseClicked
    private void AcomodarContenido() throws NegocioException {

        this.pnlFondo.setLayout(new GridBagLayout()); // Permite centrar componentes dentro

        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor del componente
        gbc.fill = GridBagConstraints.HORIZONTAL; // Centrado en la celda
        gbc.weightx = 1.0; // Espacio extra para centrar horizontalmente

        // Columna 1
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH; // Alarga la tabla con el tamaño.
        this.jTableCompras.setModel(this.LlenarTabla());
        JTableHeader header = new JTableHeader(this.jTableCompras.getColumnModel());
        this.pnlFondo.add(header, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.jTableCompras, gbc);
        this.jTableCompras.setPreferredSize(new Dimension(750, 750));
        gbc.gridy++;

//         Columna 2
        gbc.gridx = 2;
        gbc.gridy = 0;
        this.pnlFondo.add(this.lblNombreProducto, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.txtNombreProducto, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.lblProveedor, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.txtProveedor, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.lblFechaInicio, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.datePickerInicio, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.lblFechaFin, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.datePickerFin, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.jButtonConfirmar, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.jButtonEliminar, gbc);
        gbc.gridy++;
        this.jButtonEliminar.setVisible(false);
        this.pnlFondo.add(this.jButtonVolver, gbc);
        gbc.gridy++;


    }

    public int contarPaginas(int nPaginas) {
        int totalPaginas = (int) Math.ceil((double) nPaginas / 8);
        return totalPaginas;
    }

    // Metodo para llenar la tabla de Productos.
    public DefaultTableModel LlenarTabla() throws NegocioException {

        // Esto es para despues, con los botones siguiente y atras
        int index = 1;
        int aux = 1;
        int min = 1;
        int max = 0;
//        max = this.contarPaginas(ControlGUI.getInstancia().ObtenerProductos().size());
        //Tabla
        DefaultTableModel model = (DefaultTableModel) this.jTableCompras.getModel();
        model.setRowCount(0); // Limpiar todas las filas existentes en la tabla
        return model;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmConsultarCompras().setVisible(true);
                } catch (NegocioException ex) {
                    Logger.getLogger(frmConsultarCompras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePickerFin;
    private com.github.lgooddatepicker.components.DatePicker datePickerInicio;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables

}
