/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.inventario;

import Control.ControlGUI;
import excepciones.NegocioException;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joelr
 */
public class frmActualizarProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmActualizarProducto() {
        initComponents();
        this.setExtendedState(frmActualizarProducto.MAXIMIZED_BOTH);
        this.combobox();
        this.AcomodarContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 600));

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 153));
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        pnlFormulario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio Venta:");
        lblPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoria.setText("Estado:");
        pnlFormulario.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 80, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 22));

        txtPrecioVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 22));

        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFormulario.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 22));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, 32));

        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 111, 32));

        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStock.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 120, 22));

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock:");
        pnlFormulario.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 70, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 102));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Actualizar Producto");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        try {
            this.Actualizar();
            JOptionPane.showMessageDialog(rootPane, "Se registro el producto con exito");
        } catch (NegocioException ex) {
            Logger.getLogger(frmActualizarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        ControlGUI.getInstancia().mostrarMenuProducto();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void Actualizar() throws NegocioException {
       

    }
    public void combobox(){
        this.jComboBoxCategoria.addItem("General");

    }
    /**
     * Metodo para el ajuste de los componentes cuando la pantalla cambie de
     * tamaño.
     */

    private void AcomodarContenido() {
        JPanel panel = this.pnlFormulario;
        this.pnlFormulario.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.weightx = 1.0; // Cada componente se expandirá horizontalmente de manera uniforme.
        gbc.fill = GridBagConstraints.HORIZONTAL; // Hace que el componente llene el espacio horizontalmente.
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor del componente.

        // Columna 0
        gbc.gridx = 0;
        panel.add(this.lblNombre, gbc);
        gbc.gridy++;
        panel.add(this.lblPrecio, gbc);
        gbc.gridy++;
  

        // Columna 1
        gbc.gridx = 1;
        gbc.gridy = 0;
        panel.add(this.txtNombre, gbc);
        gbc.gridy++;
        panel.add(this.txtPrecioVenta, gbc);
        gbc.gridy++;
        panel.add(this.jButtonCancelar, gbc);
        gbc.gridy++;
        panel.add(this.jButtonRegistrar, gbc);

        // Columna 2
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel.add(this.lblCategoria, gbc);
        gbc.gridy++;
        panel.add(this.lblStock, gbc);
        gbc.gridy++;

        // Columna 3
        gbc.gridx = 3;
        gbc.gridy = 0;
        panel.add(this.jComboBoxCategoria, gbc);
        gbc.gridy++;
        panel.add(this.txtStock, gbc);
        gbc.gridy++;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActualizarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

}
