/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.inventario;

import Control.ControlGUI;
import DTO.ProductoDTO;
import excepciones.NegocioException;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joelr
 */
public class frmActualizarProducto extends javax.swing.JFrame {

    String nombre;
    String id;
    ProductoDTO productoElegido;
    ProductoDTO productoActualizado;

    /**
     * Creates new form RegistrarProductoGUI
     *
     * @param nombre
     */
    public frmActualizarProducto(String nombre) throws NegocioException {
        initComponents();
        this.setExtendedState(frmActualizarProducto.MAXIMIZED_BOTH);
        this.combobox();
        this.AcomodarContenido();
        this.nombre = nombre;
        this.inicial();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxUnidad = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        lblUnidad = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        lblPrecio2 = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 600));

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 153));
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSKU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKU.setText("SKU:");
        pnlFormulario.add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        pnlFormulario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio Venta:");
        lblPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoria.setText("Categoría:");
        pnlFormulario.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 110, -1));

        txtSKU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSKU.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 22));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 22));

        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 22));

        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFormulario.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 110, 22));

        jComboBoxUnidad.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFormulario.add(jComboBoxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, 22));

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, 32));

        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 111, 32));

        lblUnidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidad.setText("Unidad de Medida:");
        pnlFormulario.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 210, -1));

        txtPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioCompra.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 120, 22));

        lblPrecio2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio2.setText("Precio Compra:");
        lblPrecio2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, 30));

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProveedor.setText("Proveedor:");
        pnlFormulario.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProveedor.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 120, 22));

        lblObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservaciones.setText("Observaciones:");
        pnlFormulario.add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        txtObservaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtObservaciones.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 280, 110));

        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStock.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 120, 22));

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock Inicial:");
        pnlFormulario.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 140, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 102));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Actualizar producto");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed

        try {
            this.actualizar();
            JOptionPane.showMessageDialog(rootPane, "Se actualizo el producto con exito");
            this.dispose();
            ControlGUI.getInstancia().mostrarProductosRegistrados();
        } catch (NegocioException ex) {
            Logger.getLogger(frmActualizarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
            ControlGUI.getInstancia().mostrarProductosRegistrados();
        } catch (NegocioException ex) {
            Logger.getLogger(frmActualizarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();


    }//GEN-LAST:event_jButtonCancelarActionPerformed
    /*
    Metodo para colocar los datos del Producto a actualizar en cada campo para su visualización.
     */
    private void inicial() throws NegocioException {

        productoElegido = ControlGUI.getInstancia().obtenerProductoPorNombre(nombre);
        id = productoElegido.getId();
        if (productoElegido.getNombre() == null || productoElegido.getNombre().equalsIgnoreCase("")) {
            this.txtNombre.setText("No registrado");
        } else {
            this.txtNombre.setText(productoElegido.getNombre());
        }
        if (productoElegido.getObservaciones() == null || productoElegido.getObservaciones().equalsIgnoreCase("")) {
            this.txtObservaciones.setText("No registrado");
        } else {
            this.txtObservaciones.setText(productoElegido.getObservaciones());
        }
        if (productoElegido.getSKU() == null || productoElegido.getSKU().equalsIgnoreCase("")) {
            this.txtSKU.setText("No registrado");
        } else {
            this.txtSKU.setText(productoElegido.getSKU());
        }
        if (productoElegido.getPrecioCompraReferencial() == null) {
            this.txtPrecioCompra.setText("No registrado");
        } else {
            this.txtPrecioCompra.setText(Double.toString(productoElegido.getPrecioCompraReferencial()));
        }
        if (productoElegido.getStock() == null) {
            this.txtStock.setText("No registrado");
        } else {
            this.txtStock.setText(Integer.toString(productoElegido.getStock()));
        }
        if (productoElegido.getProveedor() == null || productoElegido.getProveedor().equalsIgnoreCase("")) {
            this.txtProveedor.setText("No registrado");
        } else {
            this.txtProveedor.setText(productoElegido.getProveedor());
        }
        this.txtPrecioVenta.setText(Double.toString(productoElegido.getPrecioVenta()));

    }

    private void actualizar() throws NegocioException {

        if (ControlGUI.getInstancia().ValidarRegistroProductoActualizar(this.txtSKU.getText(),
                this.txtNombre.getText(),
                this.txtPrecioVenta.getText(),
                this.txtPrecioCompra.getText(),
                this.txtStock.getText(), id) == true) {
            productoActualizado = ControlGUI.getInstancia().obtenerProductoPorID(id);
            productoActualizado.setNombre(this.txtNombre.getText());
            if (this.txtSKU.getText().equalsIgnoreCase("No registrado")) {
                productoActualizado.setSKU("");
            } else {
                productoActualizado.setSKU(this.txtSKU.getText());
            }
            if (this.txtPrecioCompra.getText().equalsIgnoreCase("No registrado")) {
                productoActualizado.setPrecioCompraReferencial(null);
            } else {
                productoActualizado.setPrecioCompraReferencial(Double.valueOf(this.txtPrecioCompra.getText()));
            }
            if (this.txtStock.getText().equalsIgnoreCase("No registrado")) {
                productoActualizado.setStock(null);
            } else {
                productoActualizado.setStock(Integer.valueOf(this.txtStock.getText()));
            }
            if (this.txtProveedor.getText().equalsIgnoreCase("No registrado")) {
                productoActualizado.setProveedor("");
            } else {
                productoActualizado.setProveedor(this.txtProveedor.getText());
            }
            if (this.txtObservaciones.getText().equalsIgnoreCase("No registrado")) {
                productoActualizado.setObservaciones("");

            } else {
                productoActualizado.setObservaciones(this.txtObservaciones.getText());
            }
            productoActualizado.setCategoria(this.jComboBoxCategoria.getItemAt(this.jComboBoxCategoria.getSelectedIndex()));
            productoActualizado.setUnidadMedida(this.jComboBoxUnidad.getItemAt(this.jComboBoxUnidad.getSelectedIndex()));
            productoActualizado.setPrecioVenta(Double.valueOf(this.txtPrecioVenta.getText()));

            ControlGUI.getInstancia().ActualizarProducto(productoActualizado);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error: Verifique sus campos");
            throw new NegocioException("Verifique los campos");
        }

    }

    public void combobox() {
        this.jComboBoxCategoria.addItem("General");
        this.jComboBoxUnidad.addItem("KG");
        this.jComboBoxUnidad.addItem("Litros");
        this.jComboBoxUnidad.addItem("Gramos");
    }

    /**
     * Metodo para el ajuste de los componentes cuando la pantalla cambie de
     * tamaño.
     */
    private void AcomodarContenido() {
        JPanel panel = this.pnlFormulario;
        this.pnlFormulario.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.weightx = 1.0; // Cada componente se expandirá horizontalmente de manera uniforme.
        gbc.fill = GridBagConstraints.HORIZONTAL; // Hace que el componente llene el espacio horizontalmente.
        gbc.insets = new Insets(5, 5, 5, 5); // Margen alrededor del componente.

        // Columna 0
        gbc.gridx = 0;
        panel.add(this.lblSKU, gbc);
        gbc.gridy++;
        panel.add(this.lblNombre, gbc);
        gbc.gridy++;
        panel.add(this.lblPrecio, gbc);
        gbc.gridy++;
        panel.add(this.lblPrecio2, gbc);
        gbc.gridy++;
        panel.add(this.lblProveedor, gbc);
        gbc.gridy++;

        // Columna 1
        gbc.gridx = 1;
        gbc.gridy = 0;
        panel.add(this.txtSKU, gbc);
        gbc.gridy++;
        panel.add(this.txtNombre, gbc);
        gbc.gridy++;
        panel.add(this.txtPrecioVenta, gbc);
        gbc.gridy++;
        panel.add(this.txtPrecioCompra, gbc);
        gbc.gridy++;
        panel.add(this.txtProveedor, gbc);
        gbc.gridy++;
        panel.add(this.jButtonCancelar, gbc);
        gbc.gridy++;
        panel.add(this.jButtonActualizar, gbc);

        // Columna 2
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel.add(this.lblObservaciones, gbc);
        gbc.gridy++;
        panel.add(this.lblUnidad, gbc);
        gbc.gridy++;
        panel.add(this.lblCategoria, gbc);
        gbc.gridy++;
        panel.add(this.lblStock, gbc);
        gbc.gridy++;

        // Columna 3
        gbc.gridx = 3;
        gbc.gridy = 0;
        panel.add(this.txtObservaciones, gbc);
        gbc.gridy++;
        panel.add(this.jComboBoxUnidad, gbc);
        gbc.gridy++;
        panel.add(this.jComboBoxCategoria, gbc);
        gbc.gridy++;
        panel.add(this.txtStock, gbc);
        gbc.gridy++;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxUnidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

}
