/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.inventario;

import Control.ControlGUI;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author joelr
 */
public class frmProductosRegistrados extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductoGUI
     */
    public frmProductosRegistrados() {
        initComponents();
        this.setExtendedState(frmProductosRegistrados.MAXIMIZED_BOTH);
        this.AcomodarContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 204, 153));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setBackground(new java.awt.Color(255, 204, 153));
        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        pnlFondo.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 130, 40));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        pnlFondo.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Nombre", "Categoria", "UnidadMedida", "PrecioVenta", "PrecioCompra", "Stock", "Proveedor", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneProductos.setViewportView(jTableProductos);

        pnlFondo.add(jScrollPaneProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 890, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 190, 22));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio Venta:");
        lblPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFondo.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 140, -1));

        txtPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecioVenta.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFondo.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 120, 22));

        lblStock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setText("Stock:");
        pnlFondo.add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 70, -1));

        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStock.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFondo.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 120, 22));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Estado:");
        pnlFondo.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 80, -1));

        jComboBoxEstado.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFondo.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 120, 22));

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 102));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Menu Inventario");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        ControlGUI.getInstancia().mostrarMenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed
    private void AcomodarContenido() {
        this.pnlFondo.setLayout(new GridBagLayout()); // Permite centrar componentes dentro
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = 0; // Todos estarán en la misma fila (fila 0), se incrementa para mover a la siguiente fila.
        gbc.insets = new Insets(2, 2, 2, 2); // Margen alrededor del componente
//        gbc.fill = GridBagConstraints.HORIZONTAL; // Centrado en la celda
        gbc.weightx = 1.0; // Espacio extra para centrar horizontalmente
        
        // Columna 0
        gbc.gridx = 0;   
        gbc.gridy = 1;
        this.pnlFondo.add(this.lblNombre, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.txtNombre,gbc);
        gbc.gridy++;   
        this.pnlFondo.add(this.lblPrecio, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.txtPrecioVenta,gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.lblStock, gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.txtStock,gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.lblEstado, gbc);
        gbc.gridy++;
          this.pnlFondo.add(this.jComboBoxEstado,gbc);
        gbc.gridy++;
        this.pnlFondo.add(this.jButtonVolver, gbc);
        gbc.gridy++;
        
        
//         Columna 2
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL; // Alarga la tabla con el tamaño.
        this.pnlFondo.add(this.jScrollPaneProductos, gbc);
        gbc.gridy++;
    }

    public void llenarTabla() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductosRegistrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

}
