/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modulo.inventario;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Beto_
 */
public class RegistrarProductoGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductoGUI
     */
    public RegistrarProductoGUI() {
        initComponents();
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblSKU1 = new javax.swing.JLabel();
        lblSKU2 = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblSKU3 = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 600));
        setSize(new java.awt.Dimension(750, 600));

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 153));
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSKU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKU.setText("SKU:");
        pnlFormulario.add(lblSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre:");
        pnlFormulario.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio:");
        lblPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlFormulario.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 94, -1));

        lblSKU1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU1.setText("Categoría:");
        pnlFormulario.add(lblSKU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        lblSKU2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKU2.setText("De medida:");
        pnlFormulario.add(lblSKU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txtSKU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSKU.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 22));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 22));

        txtPrecio.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 22));

        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFormulario.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 110, 22));

        jComboBox2.setPreferredSize(new java.awt.Dimension(150, 40));
        pnlFormulario.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 22));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setPreferredSize(new java.awt.Dimension(130, 45));
        pnlFormulario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 32));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.setPreferredSize(new java.awt.Dimension(130, 45));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 111, 32));

        lblSKU3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSKU3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSKU3.setText("Unidad");
        pnlFormulario.add(lblSKU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 120, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 102));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrar producto");
        pnlTitulo.add(lblTitulo, new java.awt.GridBagConstraints());

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProductoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblSKU1;
    private javax.swing.JLabel lblSKU2;
    private javax.swing.JLabel lblSKU3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSKU;
    // End of variables declaration//GEN-END:variables
    
    
}
