/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ferreplus_presentacion;

import modulo.inventario.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Beto_
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProductoGUI
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFormulario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();
        lblContrasena = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 700));
        setSize(new java.awt.Dimension(600, 600));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 153));
        pnlFormulario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnlFormularioComponentResized(evt);
            }
        });
        pnlFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        pnlFormulario.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 120, -1));

        txtUsuario.setPreferredSize(new java.awt.Dimension(200, 50));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlFormulario.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 120, 22));

        txtContrasena.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlFormulario.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, 22));

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setPreferredSize(new java.awt.Dimension(130, 45));
        pnlFormulario.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 120, 32));

        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setPreferredSize(new java.awt.Dimension(130, 45));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        pnlFormulario.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 120, 32));

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasena.setText("Contraseña");
        pnlFormulario.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 160, -1));

        getContentPane().add(pnlFormulario, java.awt.BorderLayout.CENTER);

        pnlTitulo.setBackground(new java.awt.Color(102, 51, 0));
        pnlTitulo.setDoubleBuffered(false);
        pnlTitulo.setPreferredSize(new java.awt.Dimension(400, 105));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("FERRE-PLUS");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 32, -1, -1));

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);
        pnlTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        if (this.txtUsuario.getText().isEmpty() && this.txtContrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir un usuario y una contraseña para ingresar");
        } else if (this.txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir un usuario");
        } else if (this.txtContrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe escribir una contraseña");
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void pnlFormularioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlFormularioComponentResized
//   this.componentResized(evt);
    }//GEN-LAST:event_pnlFormularioComponentResized

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
      
    }//GEN-LAST:event_formWindowStateChanged

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    // Escuchamos cuando se cambia el tamaño de la ventana

    public void componentResized(ComponentEvent e) {
        // Redimensionamos el panel base
        this.lblUsuario.setLocation(this.getHeight()/2, this.getWidth()/2);

//        this.pnlTitulo.setBounds(0, 0, this.pnlTitulo.getWidth(), this.pnlTitulo.getHeight());
//        this.pnlFormulario.setBounds(0, 0, this.pnlFormulario.getWidth(), this.pnlFormulario.getHeight());

        // Aquí puedes ajustar el tamaño/posición de los componentes
        // Por ejemplo, el botón se mantiene centrado
//                int newX = (this.pnlFormulario.getWidth() - this.pnlFormulario.getWidth()) / 2;
//                int newY = (this.pnlFormulario.getHeight() - this.pnlFormulario.getHeight()) / 2;
//                int newX2 = (this.pnlTitulo.getWidth() - this.pnlTitulo.getWidth()) / 2;
//                int newY2 = (this.pnlTitulo.getHeight() - this.pnlTitulo.getHeight()) / 2;
//                this.lblUsuario.setLocation(newX, newY);
//                this.lblContrasena.setLocation(newX, newY);
//                this.lblUsuario.setLocation(newX2, newY2);
    }

    ;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
